### ISSUE TITLE
Can you use a more liberal license like Apache V2?

### ISSUE THREAD

**Issue by stephanrauh** [jdesmet/zakee-web#1]
First of all, let me thank you for the good work! Plus extra thanks for using BootsFaces! :)

Would you mind to change the project to a more liberal license? Currently, I can't use you starter template in any of my customer projects. Because that'd mean putting the customer project under a GPL V3.0 license. My customers won't agree with that.

Is there a specific reason to choose GPL V3? If not, I'd suggest Apache V2. 

Thanks in advance,
Stephan

**Comment by jdesmet** [comment]
I have no problem changing the license. Either way, the starter is mostly the pom.xml, which doesn't make sense for slamming much of any restriction. If apache is the more liberal one then I will make it so, as soon as I sit in front of a real computer.

**Comment by stephanrauh** [comment]
Thanks!
Stephan
